### ISSUE TITLE
Trouble with hover events and clicks.

### ISSUE THREAD

**Issue by isTravis** [BowlingX/marklib#12]
Thanks for a great tool!

I'm having problems getting hover functionality and click events to work on my rendered ranges. I have something like the following:

``` js
import { Rendering } from 'marklib';

const range = <my range>;
const renderer = new Rendering(document, { hoverClass: 'highlight-hover', className: 'highlight' });
const onClick = function(instance) {
    console.log('Hello there');
};
renderer.on('click', onClick);
renderer.renderWithRange(range);
```

This properly wraps the content in x-markers and applies the highlight class. The highlight class specifies a background-color and `cursor: pointer`. The pointer cursor properly renders when I hover the xmarker, so I know that the css class is being applied, and that I don't have some weird z-index occlusion or `pointer-events: none` bug. 

When hovering, no hover-class is applied. When clicking, my console.log statement never fires.

I've also tried:
```js
Rendering.globalEmitter().on('click', function() {
    console.log('Howdy');
});
```
but that hasn't worked either.

I see this line in the README - but I'm not quite sure what it means: `Before you can actually receive events, you need to register the event handler with registerEvents`. Looking at your [Site.js](https://github.com/BowlingX/marklib/blob/master/src/main/modules/Site.js) also doesn't provide any clues. It seems rather straightforward, yet I can't find my bug. 

Any hunches?

Thanks again!

**Comment by BowlingX** [comment]
Hi,
sorry for the late reply.

You have to call `registerEvents` from `import { registerEvents } from 'marklib/src/main/RenderingEvents';` after your application loaded.
