### ISSUE TITLE
An easy way to remove x-markers

### ISSUE THREAD

**Issue by tanertopal** [BowlingX/marklib#8]
As far as I can see there is no method to remove once rendered markers. Just asking to be sure. I would try to implement one and provide create PR.

**Comment by BowlingX** [comment]
That's true. The reason is that removing tags and restoring the textnodes is not trivial (or impossible), especially when serialization should be reliable. The easiest way to "remove" is to remove the classes of a selection. This part is missing right now but I appreciate any help :).

**Comment by tanertopal** [comment]
Actually I just realized that too. It will change to DOM structure and markers which where added later will break if I remove a marker which was added earlier. Changing even the classNames would break it I guess. Need to check that anyway.

**Comment by BowlingX** [comment]
Changing the classNames will not affect the serialization, it takes the information trough data attributes.

**Comment by BowlingX** [comment]
There is a new Method `destroy` (master branch) now that will do some cleanup and also remove all classes from highlight nodes.

**Comment by ZachSaucier** [comment]
I [tried using this method](http://jsfiddle.net/Zeaklous/qmz2pLws/39/) based on the `site.js` but it doesn't seem to be working for me.

P. S. Is there any version of the JS and CSS that isn't bundled with the demo's JS and CSS?
